### ISSUE TITLE
upsupported data type and question about cell type 

### ISSUE THREAD

**Issue by x9m** [meshpro/pygalmesh#172]
Hi,
I have two questions about the elephant example.

the first one is when I import the elephant volume mesh into Paraview(version 5.9). it gave me this error message:
```
ERROR: In C:\glr\builds\paraview\paraview-ci\build\superbuild\paraview\src\VTK\IO\Legacy\vtkDataReader.cxx, line 2025
vtkUnstructuredGridReader (0000014B4963B440): Unsupported data type: vtktypeint32
```
next one is  when i clicked the cell type column in spreadsheetview. it showed tetrahedron and triangle at same time. but, since i  did the conversion from surface to volume why is there some triangle cell type?

will it cause any problems if I pass it to a FEM solver? or should i remove the triangle somehow?

I really appreciate if someone can help me on these issues. thanks in advance.

**Comment by nschloe** [comment]
> the first one is when I import the elephant volume mesh into Paraview(version 5.9). it gave me this error message:

I cannot reproduce this.

> but, since i did the conversion from surface to volume why is there some triangle cell type?

The surface cells are not deleted.

**Comment by x9m** [comment]
Hi nschloe,

Thank you for your reply.

regarding to my 2nd question, do you know how to delete the surface cells?

cheers

**Comment by nschloe** [comment]
You'll have to juggle around with the cell types a bit. Just check out `cells` and perhaps `cell_data` and `cell_sets` and remove the respective entries.
